version: 2

project_name: gheppo

before:
  hooks:
    - go mod tidy

builds:
  - id: gheppo
    main: .
    binary: gheppo
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - id: default
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip

checksum:
  name_template: "checksums.txt"

release:
  github:
    owner: dexisback
    name: gheppo
